### ISSUE TITLE
Submit album information to Last.fm when scrobbling

### ISSUE THREAD

**Issue by neilmenon** [stephanebruckert/ShazamScrobbler#37]
Shazam Scrobbler is excellent, but one thing it is lacking is not submitting the album of the song to Last.fm with the scrobble. I know Shazam probably doesn't provide this information since a song doesn't need to be tied to an album, but I noticed that when a song is scrobbled on the Shazam app, an Apple Music link is provided:
![image](https://user-images.githubusercontent.com/47338272/140426039-c01fa813-b804-44ec-b148-58cd023e5de1.png)

That Apple music link could be scraped to determine the album title, which in turn could be submitted to the Last.fm API when the track is scrobbled.

The reason this is important is because, although in Last.fm the scrobbled song counts towards artist scrobbles and individual track scrobbles, it does not bump your album scrobbles of that track.

Thanks!

**Comment by stephanebruckert** [comment]
Hey, glad you find the app useful and thanks for the improvement idea!

Looks like the album is available as part of the `ZSHMETADATAMO` sqlite table stored by Shazam.app, so that's doable without scraping the apple music link. 👍 

<img width="1304" alt="Screenshot 2021-11-05 at 16 51 59" src="https://user-images.githubusercontent.com/1932338/140548321-3592460a-5078-4dbe-aa8a-398d42ee22de.png">

It would be about enhancing this query to also fetch the album name:

https://github.com/ShazamScrobbler/shazamscrobbler-macos/blob/da005241aed6e14ca119fd617667cd1caba15b9e/ShazamScrobbler/ShazamController.m#L170

and pass it here filling in `onAlbum`:

https://github.com/ShazamScrobbler/shazamscrobbler-macos/blob/da005241aed6e14ca119fd617667cd1caba15b9e/ShazamScrobbler/LastFmController.m#L135

I can't promise I will have time to do the fix soon, so if you or anyone else wants to have a quick go at it that would be amazing!

**Comment by neilmenon** [comment]
@stephanebruckert - awesome... created PR for this enhancement. Not sure how to build on my own, but please test and let me know if it works!

https://github.com/ShazamScrobbler/shazamscrobbler-macos/pull/38

**Comment by stephanebruckert** [comment]
@neilmenon released in 1.3.0 https://github.com/ShazamScrobbler/shazamscrobbler-macos/releases/tag/1.3.0
